import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { locales } from "../../middleware";
import { notFound } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}) {
  if (!locales.includes(locale)) notFound();
  return (
    <html lang={locale}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
